In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40])
print(arr)

[10 20 30 40]


In [ ]:
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr = np.arange(1,13)
print(arr.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr.shape)
print(arr.size)

(2, 3)
6


In [ ]:
arr = np.linspace(1, 10, 5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
arr = np.full((3, 4), 7)
print(arr)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
arr = np.array([[10, 20, 30],[40, 50, 60]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.T)

(2, 3)
2
6
int64
[[10 40]
 [20 50]
 [30 60]]


In [ ]:
arr = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

print(arr)
print(arr.ndim)   # Number of dimensions
print(arr.shape)  # (Layers, Rows, Columns)
print(arr.size)   # Total number of elements
print(arr[0])        # First layer
print(arr[1])        # Second layer
print(arr[0][1])     # Second row of first layer
print(arr[1][0][0])  # Element 9

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)
12
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[4 5 6]
7


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(2, 3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr_1 = np.reshape(arr,(3,2))
print(new_arr_1)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
arr_3d = np.array([1,2,3,4,5,6,7,8])
new_arr_3d = arr_3d.reshape(2,2,2)
print(new_arr_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr[1:5])
print(arr[:4])
print(arr[2:])
print(arr[::2])

[20 30 40 50]
[10 20 30 40]
[30 40 50 60]
[10 30 50]


In [ ]:
import numpy as np
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
print(arr[0:2,1:3])
print(arr[1,:])
print(arr[:,2])

[[20 30]
 [50 60]]
[40 50 60]
[30 60 90]


In [ ]:
import numpy as np
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(arr[0,:,:])
print(arr[1,1,:])
print(arr[:,:,0])

[[1 2 3]
 [4 5 6]]
[10 11 12]
[[ 1  4]
 [ 7 10]]


In [ ]:
import numpy as np

a = np.array([10,20,30])
b = np.array([2,4,5])
print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)
print("Floor Division:", a//b)
print("Modulus:", a%b)
print("Power:", a**2)

Addition: [12 24 35]
Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division: [5. 5. 6.]
Floor Division: [5 5 6]
Modulus: [0 0 0]
Power: [100 400 900]


2. Mathematical Functions:
| Function      | Purpose                   | Example            |
| ------------- | ------------------------- | ------------------ |
| `np.sqrt()`   | Square root               | `np.sqrt(arr)`     |
| `np.square()` | Square of each element    | `np.square(arr)`   |
| `np.power()`  | Raise elements to a power | `np.power(arr, 3)` |
| `np.abs()`    | Absolute value            | `np.abs(arr)`      |
| `np.exp()`    | Exponential (eˣ)          | `np.exp(arr)`      |
| `np.log()`    | Natural logarithm         | `np.log(arr)`      |
| `np.log10()`  | Base-10 logarithm         | `np.log10(arr)`    |
| `np.sin()`    | Sine                      | `np.sin(arr)`      |
| `np.cos()`    | Cosine                    | `np.cos(arr)`      |
| `np.tan()`    | Tangent                   | `np.tan(arr)`      |
| `np.round()`  | Round to nearest integer  | `np.round(arr)`    |
| `np.ceil()`   | Round up                  | `np.ceil(arr)`     |
| `np.floor()`  | Round down                | `np.floor(arr)`    |


In [ ]:
import numpy as np
# Create a NumPy array
arr = np.array([1, 4, 9, 16, 25])
print("Original Array:", arr)
# Square Root
print("\nSquare Root:", np.sqrt(arr))
# Square
print("Square:", np.square(arr))
# Cube (Power 3)
print("Cube:", np.power(arr, 3))
# Absolute Value
arr2 = np.array([-5, -10, 15, -20, 25])
print("\nAbsolute Value:", np.abs(arr2))
# Exponential (e^x)
print("\nExponential:", np.exp(arr))
# Natural Logarithm
print("\nNatural Log:", np.log(arr))
# Base-10 Logarithm
print("Log Base 10:", np.log10(arr))
# Sine
print("\nSine:", np.sin(arr))
# Cosine
print("Cosine:", np.cos(arr))
# Tangent
print("Tangent:", np.tan(arr))
# Round Values
decimal = np.array([2.34, 4.67, 8.91, 6.28])
print("\nRounded Values:", np.round(decimal))
# Ceiling
print("Ceiling:", np.ceil(decimal))
# Floor
print("Floor:", np.floor(decimal))

Original Array: [ 1  4  9 16 25]

Square Root: [1. 2. 3. 4. 5.]
Square: [  1  16  81 256 625]
Cube: [    1    64   729  4096 15625]

Absolute Value: [ 5 10 15 20 25]

Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]

Natural Log: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
Log Base 10: [0.         0.60205999 0.95424251 1.20411998 1.39794001]

Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
Cosine: [ 0.54030231 -0.65364362 -0.91113026 -0.95765948  0.99120281]
Tangent: [ 1.55740772  1.15782128 -0.45231566  0.30063224 -0.13352641]

Rounded Values: [2. 5. 9. 6.]
Ceiling: [3. 5. 9. 7.]
Floor: [2. 4. 8. 6.]


In [ ]:
import numpy as np

# Create a NumPy array
marks = np.array([75, 82, 90, 68, 95, 88, 79])

print("Original Array:", marks)
# Sort
print("Sorted Array:", np.sort(marks))
# Sum
print("\nSum:", np.sum(marks))

# Mean (Average)
print("Mean:", np.mean(marks))

# Median
print("Median:", np.median(marks))

# Maximum Value
print("Maximum:", np.max(marks))

# Minimum Value
print("Minimum:", np.min(marks))

# Range
print("Range:", np.ptp(marks))

# Standard Deviation
print("Standard Deviation:", np.std(marks))

# Variance
print("Variance:", np.var(marks))

# Index of Maximum Value
print("Index of Maximum:", np.argmax(marks))

# Index of Minimum Value
print("Index of Minimum:", np.argmin(marks))

# Percentiles
print("25th Percentile:", np.percentile(marks, 25))
print("50th Percentile:", np.percentile(marks, 50))
print("75th Percentile:", np.percentile(marks, 75))

In [ ]:
import numpy as np

# Random number
print(np.random.rand())

# Random numbers
print(np.random.rand(5))

# Random integers
print(np.random.randint(1, 11, 5))

# Random choice
subjects = ["DBMS", "Python", "Java", "ML"]
print(np.random.choice(subjects))

# Normal distribution
print(np.random.normal(50, 10, 5))

# Uniform distribution
print(np.random.uniform(10, 20, 5))

# Bernoulli random variable
print(np.random.binomial(1, 0.5))

# Binomial random variable
print(np.random.binomial(10, 0.7))

# Poisson random variable
print(np.random.poisson(4, 5))

# Exponential random variable
print(np.random.exponential(2, 5))